version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/expense-tracker
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - mern

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/expense-tracker
    networks:
      - mern
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern

volumes:
  mongodb_data:
    driver: local

networks:
  mern:
    driver: bridge
